esphome:
  name: esp32envir
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "HANZE-IN01"
  password: "Aux359MHZ7"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32Envir Fallback Hotspot"
    password: "7LsBAVsEmDol"

captive_portal:

# Enable logging
logger:
 level: DEBUG

# Enable Home Assistant API
api:
  password: "environ"

ota:
  safe_mode: True
  password: "environ"

i2c:
  sda: 26
  scl: 27
  scan: True
  id: bus_a

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
