esphome:
  name: test1
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "HANZE-IN01"
  password: "Aux359MHZ7"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: " Fallback Hotspot"
    password: "xarAGU6rD6sS"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "environ"

ota:
  password: "environ"
i2c:
  sda: 21
  scl: 22
  scan: True
  id: bus_a

binary_sensor:
  - platform: gpio
    name: "Living Room Window"
    pin:
      number: 16
      inverted: True
      mode: INPUT_PULLUP

sensor:
  - platform: bme680
    temperature:
      name: "BME680 Temperature"
      oversampling: 16x
    pressure:
      name: "BME680 Pressure"
    humidity:
      name: "BME680 Humidity"
    gas_resistance:
      name: "BME680 Gas Resistance"
    address: 0x70
    update_interval: 60s

 sensor:
  - platform: dht
    pin: D14
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 60s

