esphome:
  name: esp32envir
  platform: ESP32
  board: nodemcu-32s
  includes:
    - my_custom_sensor.h
  libraries:
    - metriful_sensor.h
wifi:
  ssid: "HANZE-IN01"
  password: "Aux359MHZ7"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32Envir Fallback Hotspot"
    password: "7LsBAVsEmDol"

captive_portal:

# Enable logging
logger:
 level: DEBUG

# Enable Home Assistant API
api:
  password: "environ"

ota:
  safe_mode: True
  password: "environ"

sensor:
- platform: custom
  lambda: |-
    auto my_sensor = new MyCustomSensor();
    App.register_component(my_sensor);
    return {my_sensor->temperature_sensor, my_sensor->pressure_sensor, my_sensor->light_sensor, my_sensor->humidity_sensor, my_sensor->sound pressure level_sensor};

  sensors:
  - name: "BME680 Temperature Sensor"
    unit_of_measurement: °C
    accuracy_decimals: 1
  - name: "BME680 Pressure Sensor"
    unit_of_measurement: hPa
    accuracy_decimals: 2
  - name: "BME680 Humidity Sensor"
    unit_of_measurement: RH
    accuracy_decimals: 2
  - name: "Vishay VEML6030 light Sensor"
    unit_of_measurement: LUX
    accuracy_decimals: 2
  - name: "Knowles SPH0645LM4H-B mems microphone"
    unit_of_measurement: dB
    accuracy_decimals: 2
  - name: "BME680 VOC Sensor"
    unit_of_measurement: ppm/int
    accuracy_decimals: 2
